# Generated by Django 4.2.18 on 2025-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_residents_plate_number_residents_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Unknown', max_length=100)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('resident_address', models.TextField(default='Not Provided')),
                ('category', models.CharField(choices=[('Resident', 'Resident'), ('Visitor', 'Visitor'), ('Criminal', 'Criminal')], default='Resident', max_length=10)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('registered_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
