# Generated by Django 4.2.18 on 2025-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
